services:
  adminer:
    image: adminer
    restart: always
    container_name: lotus_adminer
    ports:
      - 8086:8080

  db:
    image: postgres:15.8
    restart: always
    container_name: lotus_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "2345:5432"
    volumes:
      - db:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    restart: always
    container_name: lotus_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: lotus_test
      MYSQL_USER: lotus
      MYSQL_PASSWORD: lotus
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    restart: always
    container_name: lotus_mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Lotus123!
      MSSQL_SA_PASSWORD: Lotus123!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  db:
  mysql_data:
  mssql_data:
